import type { Category } from "@/lib/themes";
import type { ControlId } from "@/graph/iconKits";

// Generated by scripts/build-icon-kits.py from the Clean and Retro icon kits.
// Regenerate it rather than editing it; the script is also where the checks
// live that catch a kit having quietly changed shape.
//
// One pictogram table serves both kits. They are the same drawings — flowing
// curves and circular details, redrawn from the angular set in iconKits.ts —
// and they differ only in what is behind them and what colour they are lit in.
// Everything is on the same -12..12 box the rest of the app draws marks on.

/** One shape of a pictogram. `f` paints it with the ink; otherwise it is stroked. */
export type CurveLayer =
  | { p: string; f?: boolean }
  | { c: [number, number, number]; f?: boolean }
  | { r: [number, number, number, number, number]; f?: boolean }
  | { e: [number, number, number, number]; t?: number; f?: boolean };

export type CurveGlyph = CurveLayer[];

/** Stroke weight the two kits draw at, in glyph units. */
export const CURVE_STROKE = 1.85;
export const RETRO_STROKE = 1.8;

export const CURVE_CATEGORY_GLYPHS: Record<Category, CurveGlyph> = {
  "adventure": [{ c: [0, 0, 10] }, { p: "M4 -4Q5 -5 4 -2L2 3-4 5Q-5 5-4 3L-2 -2Z" }],
  "community": [{ c: [0, -5, 3] }, { c: [-7, -1, 2.5] }, { c: [7, -1, 2.5] }, { p: "M-6 10C-6 1 6 1 6 10M-11 8Q-11 3-7 3M11 8Q11 3 7 3" }],
  "craft": [{ c: [-6, 6, 3] }, { c: [6, 6, 3] }, { p: "M-4 4Q1 -2 7 -10M4 4Q-1 -2-7 -10" }],
  "creative": [{ p: "M9 2C8 8 3 11-3 9C-13 6-11 -7-2 -9C5 -11 12 -6 9 -1C7 2 3 -2 3 2C3 5 7 4 9 2Z" }, { c: [-5, -3, 0.8], f: true }, { c: [0, -6, 0.8], f: true }],
  "culinary": [{ p: "M-10 2H10M-8 2C-8 -8 8 -8 8 2M0 -6V-9M-2 -9H2M-8 6Q0 9 8 6" }],
  "fitness": [{ p: "M-7 -5V5M7 -5V5M-10 -2V2M10 -2V2M-7 0H7" }],
  "mind": [{ p: "M-4 9V5C-11 1-9 -9 0 -9C9 -9 10 -2 8 2L5 4V9M-1 -3C-5 -7-7 0-3 1C-3 5 3 4 3 0C7 0 5 -6 1 -4" }],
  "nature": [{ p: "M-8 8C-10 -3-2 -9 9 -9C10 2 3 10-8 8ZM-8 8Q-1 3 4 -3" }],
  "outdoor": [{ p: "M-10 8Q-11 8-10 6L-5 -5Q-4 -7-3 -5L1 2L4 -2Q5 -4 6 -2L11 7Q11 8 9 8ZM-6 -2Q-4 1-2 -1" }, { c: [6, -7, 2] }],
  "social": [{ p: "M-5 -8H2Q7 -8 7 -3Q7 2 2 2H-2L-7 6V1Q-10 0-10 -3Q-10 -8-5 -8ZM2 5H5L9 8V4Q12 2 10 -2" }],
  "tech": [{ r: [-7, -7, 14, 14, 4] }, { r: [-2.5, -2.5, 5, 5, 1.5] }, { p: "M-10 -3H-7M-10 3H-7M7 -3H10M7 3H10M-3 -10V-7M3 -10V-7M-3 7V10M3 7V10" }],
};


export const CURVE_HOBBY_GLYPHS: Record<string, CurveGlyph> = {
  "3d-printing": [{ p: "M-9 8V-6Q-9 -9-6 -9H6Q9 -9 9 -6V8M-6 -5H6M0 -5V0M-2 0H2M-5 4Q0 0 5 4V8Q0 12-5 8ZM-5 4L0 7 5 4M0 7V10" }],
  "archery": [{ p: "M-5 -10C9 -5 9 5-5 10ZM-10 0H11M6 -4Q8 -1 11 0Q8 1 6 4" }],
  "astronomy": [{ c: [0, 0, 7] }, { e: [0, 0, 12, 4], t: -25 }],
  "baking": [{ p: "M-8 1C-13 -2-8 -8-4 -6C-3 -11 4 -11 5 -6C11 -7 13 0 8 1ZM-8 1L-6 9H6L8 1M-3 4L-2 7M2 4L3 7" }],
  "birdwatching": [{ c: [-6, 5, 4.5] }, { c: [6, 5, 4.5] }, { p: "M-10 3L-8 -8H-4L-2 3M2 3L4 -8H8L10 3M-2 0Q0 -2 2 0" }],
  "blacksmithing": [{ p: "M-10 -2H10Q8 3 2 3H0Q-2 6 3 8H6V10H-7V8H-4Q0 6-3 3Q-9 3-10 -2ZM-4 -10L1 -6M-1 -9L4 -4" }],
  "board-games": [{ r: [-9, -9, 18, 18, 5] }, { c: [-4, -4, 1], f: true }, { c: [4, 4, 1], f: true }, { c: [0, 0, 1], f: true }],
  "bookbinding": [{ p: "M0 -6Q-5 -10-10 -7V8Q-5 5 0 9Q5 5 10 8V-7Q5 -10 0 -6ZM0 -6V9" }],
  "calligraphy": [{ p: "M0 -10C-2 -5-5 -1-7 2L0 10L7 2C5 -1 2 -5 0 -10ZM0 -9V1" }, { c: [0, 2, 1.5] }],
  "chess": [{ c: [0, -7, 3] }, { p: "M-3 -4Q-2 1-6 6H6Q2 1 3 -4M-6 6Q-9 6-9 9H9Q9 6 6 6" }],
  "coding": [{ r: [-10, -8, 20, 17, 4] }, { p: "M-10 -3H10M-6 1L-3 4-6 7M1 7H5" }],
  "coffee": [{ p: "M-8 -3H5V2C5 10-8 10-8 2ZM5 -1C12 -3 12 5 5 5M-10 10Q-1 11 8 10M-4 -7C-6 -9-1 -9-3 -11M1 -7C-1 -9 4 -9 2 -11" }],
  "cooking": [{ p: "M-8 -2H8V4Q8 9 3 9H-3Q-8 9-8 4ZM-10 0H-8M8 0H10M-6 -6Q0 -9 6 -6M0 -8V-10" }],
  "cooking-club": [{ c: [0, 1, 6] }, { p: "M-10 -8V10M-7 -8V-3Q-10 0-12 -3V-8M10 -8Q6 -3 10 0V10" }],
  "cycling": [{ c: [-6, 4, 4] }, { c: [7, 4, 4] }, { p: "M-6 4L-1 -4L4 4H-6M-1 -4H5L7 4M5 -4L6 -8H9M-3 -7H0" }],
  "drawing": [{ p: "M-9 9L-7 3L5 -9Q7 -11 9 -9Q11 -7 9 -5L-3 7ZM-7 3L-3 7M3 -7L7 -3" }],
  "electronics": [{ p: "M-10 0H-6Q-5 0-4 -4L-3 -7Q-2 -9-1 -4L2 6Q3 10 4 4L5 1Q5 0 7 0H10" }],
  "fencing": [{ p: "M-8 9L8 -9M8 9L-8 -9M-9 3Q-6 7-3 9M9 3Q6 7 3 9" }],
  "fermentation": [{ p: "M-5 -10H5M-4 -10V-6Q-8 -5-8 -1V6Q-8 10-4 10H4Q8 10 8 6V-1Q8 -5 4 -6V-10M-8 1Q-3 -1 1 1Q4 3 8 1" }, { c: [-3, 5, 0.8], f: true }, { c: [3, 6, 1], f: true }],
  "foraging": [{ p: "M-10 -1H10L8 7Q8 9 5 9H-5Q-8 9-8 7ZM-6 -1C-6 -10 6 -10 6 -1M0 -6Q0 -12 7 -10Q8 -5 0 -6" }],
  "genealogy": [{ c: [0, -8, 2] }, { c: [-7, 2, 2] }, { c: [7, 2, 2] }, { p: "M0 -6V-3M-7 0V-1Q-7 -3-5 -3H5Q7 -3 7 -1V0M-7 4V7M7 4V7M-10 10V9Q-10 7-8 7H-6Q-4 7-4 9V10M7 7V10" }],
  "geology": [{ p: "M-7 9Q-10 9-10 6L-9 -2Q-8 -6-4 -8L1 -6Q4 -11 7 -8L10 2Q11 8 7 9ZM-4 -8L-3 2-6 9M1 -6L3 2 7 9M-9 -2Q0 5 10 2" }],
  "glassblowing": [{ p: "M-10 -10L1 1M1 1C6 -3 12 3 8 8C4 13-3 7 1 1M3 3Q5 1 7 4" }],
  "hiking": [{ p: "M-8 -10H-2V-3Q-1 1 5 2Q10 3 10 7V9H-8ZM-8 5Q0 6 9 6M-2 -2L-5 0M2 1L0 3" }],
  "improv": [{ p: "M-10 -8Q-5 -5 0 -7V0Q-4 8-9 2ZM0 -3Q5 -5 10 -3V5Q5 12 0 5M-7 -1Q-5 2-3 0M3 6Q5 3 8 5" }, { c: [-7, -4, 0.5], f: true }, { c: [-3, -3, 0.5], f: true }, { c: [3, 0, 0.5], f: true }, { c: [7, 0, 0.5], f: true }],
  "investing": [{ p: "M-9 8Q-4 7-2 2Q0 -2 3 1Q5 4 9 -7M3 -7H9V-1M-9 11H10" }],
  "journaling": [{ r: [-9, -10, 16, 20, 3] }, { p: "M-4 -10V10M0 -5H3M0 -1H3M2 7L4 3 9 -2Q11 -3 12 0L7 5Z" }],
  "kayaking": [{ p: "M-11 2Q0 -5 11 2Q0 11-11 2ZM-7 -9L8 8M-7 -9Q-12 -9-9 -5L-6 -6M8 8Q13 9 10 4L7 5" }],
  "language-learning": [{ c: [0, 0, 10] }, { p: "M0 -10C-7 -5-7 5 0 10C7 5 7 -5 0 -10M-9 -4H9M-10 3H10" }],
  "leatherwork": [{ p: "M-8 -8Q-2 -11 2 -7Q5 -5 9 -7C11 1 7 11-1 9Q-10 8-9 1Z" }, { p: "M-5 -4L-3 -5M3 -2L5 -1M5 4L3 6M-3 5L-5 3" }],
  "marine-biology": [{ p: "M-7 0C-2 -8 6 -6 10 0C6 6-2 8-7 0ZM-7 0L-11 -4V4ZM0 -4Q3 0 0 4" }, { c: [6, -1, 0.8], f: true }],
  "meditation": [{ p: "M0 10C-7 5-6 -5 0 -10C6 -5 7 5 0 10ZM0 10C-8 11-11 3-10 -3Q-4 -3-2 4M0 10C8 11 11 3 10 -3Q4 -3 2 4" }],
  "music": [{ p: "M-3 5V-6Q-3 -7-2 -7L7 -9Q9 -9 9 -7V3M-3 -2L9 -5" }, { e: [-6, 6, 3, 2.3], f: true }, { e: [6, 4, 3, 2.3], f: true }],
  "mycology": [{ p: "M-10 1C-10 -12 10 -12 10 1ZM-3 1V7Q0 12 3 7V1" }, { c: [-4, -3, 1], f: true }, { c: [3, -5, 1.2], f: true }],
  "parkour": [{ c: [2, -7, 2.3] }, { p: "M0 -3Q-3 0-7 -2M-1 -1Q3 3 7 -2M1 1Q5 2 8 6M1 1Q1 7-5 6M-10 10V5Q-10 4-9 4H-6" }],
  "philosophy": [{ p: "M-10 -5Q0 -15 10 -5ZM-7 -1V6M-2 -1V6M3 -1V6M8 -1V6M-10 9H10" }],
  "photography": [{ r: [-10, -5, 20, 14, 4] }, { p: "M-5 -5L-3 -8H3L5 -5" }, { c: [0, 2, 4] }, { c: [7, -1, 0.65], f: true }],
  "pottery": [{ p: "M-5 -9Q0 -8 5 -9M-4 -8C-7 -2-11 1-6 8Q0 11 6 8C11 1 7 -2 4 -8M-7 3Q0 6 7 3" }],
  "rock-climbing": [{ p: "M-10 9L-3 -7Q-1 -11 1 -7L10 9ZM-3 6Q-2 2 2 1L0 -3" }],
  "running": [{ c: [3, -7, 2.3] }, { p: "M1 -3Q-3 1 1 3Q4 5 2 10M-1 1Q-4 7-9 4M0 -2Q-5 -5-8 -1M0 -1Q5 3 8 -1" }],
  "skateboarding": [{ p: "M-10 -3Q-9 3-4 3H4Q9 3 10 -3" }, { c: [-5, 8, 2] }, { c: [5, 8, 2] }],
  "surfing": [{ p: "M-10 7C-9 -3-2 -10 5 -7C12 -4 9 4 4 3C0 2 2 -2 4 -1M-10 9Q0 12 10 8" }],
  "urban-exploration": [{ p: "M-9 9V-4Q-9 -6-7 -7L-3 -9Q-1 -10-1 -7V9M-1 -2L5 -4Q9 -5 9 -1V9M-10 9H10M3 9V4Q5 1 7 4V9M-6 -3H-4M-6 1H-4" }],
  "volunteering": [{ p: "M0 2C-11 -4-5 -12 0 -6C5 -12 11 -4 0 2ZM-10 5Q-7 4-3 7H3Q4 5 7 5Q12 5 7 8L3 10H-3L-9 8" }],
  "weaving": [{ p: "M-8 -9C-12 -3-4 3-8 9M0 -9C-4 -3 4 3 0 9M8 -9C4 -3 12 3 8 9M-10 -5C-3 -9 3 -1 10 -5M-10 3C-3 -1 3 7 10 3" }],
  "yoga": [{ c: [0, -7, 2.3] }, { p: "M0 -3V2M-7 -1Q0 5 7 -1M0 2C-3 3-14 8-5 9H5C14 8 3 3 0 2" }],
  "zumba": [{ c: [1, -7, 2.4] }, { p: "M0 -3Q-4 2 0 5L-4 10M0 5Q4 5 7 9M-1 -1Q-8 -1-9 -6M0 -2Q6 -1 8 -7" }],
};


// The tab destinations. Both kits set these in a carrier of their own, and
// both are ignored here: a tab icon travels between the active and inactive
// tint at 22pt, which neither a coloured tile nor a metal jewel survives.
export const CURVE_CONTROL_GLYPHS: Record<ControlId, CurveGlyph> = {
  "collection": [{ p: "M-10 -4V-6Q-10 -9-7 -9H-3Q-1 -9 1 -6H7Q10 -6 10 -3V6Q10 9 7 9H-7Q-10 9-10 6ZM-10 -2H10" }],
  "discover": [{ c: [0, 0, 10] }, { p: "M4 -4Q5 -5 4 -2L2 3-4 5Q-5 5-4 3L-2 -2Z" }],
  "graph": [{ p: "M-7 5Q-8 -4-1 -6Q6 -8 8 -1Q10 7 4 8Q-3 10-7 5M-1 -6Q-1 2 4 8" }, { c: [-7, 5, 1.6], f: true }, { c: [-1, -6, 1.6], f: true }, { c: [8, -1, 1.6], f: true }, { c: [4, 8, 1.6], f: true }],
  "profile": [{ c: [0, -6, 4] }, { p: "M-9 10C-9 -1 9 -1 9 10Z" }],
};


// Clean: a rounded tile behind a cluster, nothing behind a hobby.
//
// The tile's gradient is the one thing a cluster changes, and four gradients
// cover eleven clusters — the kit groups them rather than giving each its own,
// which is what keeps a screen of them from reading as a paint chart. Hobbies
// are drawn bare in the theme's own hue, so this set stays legible in all seven
// themes without a carrier to fight them.
export const CLEAN_TILE: Record<Category, [string, string]> = {
  "adventure": ["#555BDB", "#A194F5"],
  "community": ["#555BDB", "#A194F5"],
  "craft": ["#A550E3", "#EE709C"],
  "creative": ["#307DCB", "#58C3B0"],
  "culinary": ["#307DCB", "#58C3B0"],
  "fitness": ["#A550E3", "#EE709C"],
  "mind": ["#307DCB", "#58C3B0"],
  "nature": ["#E25776", "#F3AE75"],
  "outdoor": ["#555BDB", "#A194F5"],
  "social": ["#A550E3", "#EE709C"],
  "tech": ["#E25776", "#F3AE75"],
};


export const CLEAN_GLYPH = {
  category: { x: 40, y: 40, scale: 1.8 },
  hobby: { x: 40, y: 40, scale: 2.45 },
} as const;


// Retro: a brushed-metal casing with a lit screen.
//
// The accent is the colour of that screen, and the kit assigns one of six per
// icon rather than one per cluster, so it is stored per id. Three hobbies are
// drawn as a pocket music player instead of the handheld — the kit's own
// decision, detected rather than listed, so a kit that changes its mind about
// which ones is picked up on the next regeneration.
export const RETRO_ACCENT: Record<string, string> = {
  "3d-printing": "#69CDB9",
  "adventure": "#A9CB53",
  "archery": "#A9CB53",
  "astronomy": "#D7E3E9",
  "baking": "#A9CB53",
  "birdwatching": "#F0AE70",
  "blacksmithing": "#A9CB53",
  "board-games": "#739EF9",
  "bookbinding": "#D8B3F6",
  "calligraphy": "#739EF9",
  "chess": "#F0AE70",
  "coding": "#D8B3F6",
  "coffee": "#739EF9",
  "community": "#F0AE70",
  "cooking": "#D7E3E9",
  "cooking-club": "#69CDB9",
  "craft": "#D8B3F6",
  "creative": "#739EF9",
  "culinary": "#D7E3E9",
  "cycling": "#739EF9",
  "drawing": "#F0AE70",
  "electronics": "#F0AE70",
  "fencing": "#739EF9",
  "fermentation": "#D8B3F6",
  "fitness": "#A9CB53",
  "foraging": "#69CDB9",
  "genealogy": "#69CDB9",
  "geology": "#D7E3E9",
  "glassblowing": "#69CDB9",
  "hiking": "#739EF9",
  "improv": "#D2E9C0",
  "investing": "#D8B3F6",
  "journaling": "#A9CB53",
  "kayaking": "#D8B3F6",
  "language-learning": "#D2E9C0",
  "leatherwork": "#F0AE70",
  "marine-biology": "#A9CB53",
  "meditation": "#739EF9",
  "mind": "#69CDB9",
  "music": "#D2E9C0",
  "mycology": "#A9CB53",
  "nature": "#739EF9",
  "outdoor": "#D8B3F6",
  "parkour": "#D8B3F6",
  "philosophy": "#D7E3E9",
  "photography": "#69CDB9",
  "pottery": "#A9CB53",
  "rock-climbing": "#D7E3E9",
  "running": "#69CDB9",
  "skateboarding": "#D7E3E9",
  "social": "#F0AE70",
  "surfing": "#F0AE70",
  "tech": "#69CDB9",
  "urban-exploration": "#739EF9",
  "volunteering": "#69CDB9",
  "weaving": "#D7E3E9",
  "yoga": "#D8B3F6",
  "zumba": "#A9CB53",
};


export const RETRO_PLAYERS: string[] = [
  "improv",
  "language-learning",
  "music",
];


export const RETRO_GLYPH = {
  category: { x: 40, y: 39, scale: 1.2 },
  handheld: { x: 40, y: 36, scale: 1.36 },
  player: { x: 40, y: 24, scale: 0.74 },
} as const;


// The carriers, lifted verbatim. Coordinates are on the kits' own 0..80 box;
// the app maps that onto its -12..12 box at draw time, the same way the Files
// carrier is mapped, so neither kit is redrawn to fit.
export const CURVE_BOX = 80;

/** Clean's cluster tile. */
export const CLEAN_TILE_RECT = { x: 8, y: 8, size: 64, radius: 20 } as const;

/** Retro's console: a dark slab, a gloss, the lit screen, a status bar. */
export const RETRO_CONSOLE = {
  body: { x: 7, y: 12, w: 66, h: 56, r: 17 },
  bodyStroke: "#667083",
  gloss: "M16 15H63Q69 15 69 23V29Q40 19 11 37V23Q11 17 16 15Z",
  glossFill: "#DCE4EF",
  screen: { cx: 40, cy: 39, r: 21 },
  bar: { x: 32, y: 62, w: 16, h: 2, r: 1 },
} as const;

/** Retro's handheld: metal shell, inset LCD, a corner gloss, a speaker. */
export const RETRO_HANDHELD = {
  shell: { x: 9, y: 10, w: 62, h: 60, r: 10 },
  shellStroke: "#7E8994",
  screen: { x: 14, y: 16, w: 52, h: 41, r: 5 },
  screenFill: "#1A222C",
  screenStroke: "#76848D",
  gloss: "M17 19H62L17 40Z",
  light: { cx: 18, cy: 63, r: 2 },
  speaker: "M49 62H63M49 65H63",
  speakerStroke: "#6C7780",
} as const;

/** Retro's pocket player, for the three hobbies the kit draws that way. */
export const RETRO_PLAYER = {
  shell: { x: 19, y: 5, w: 42, h: 70, r: 9 },
  shellStroke: "#89939B",
  screen: { x: 24, y: 12, w: 32, h: 24, r: 3 },
  screenFill: "#323F45",
  wheel: { cx: 40, cy: 55, r: 14 },
  wheelFill: "#F8F8F3",
  wheelStroke: "#B1B7B9",
  hub: { cx: 40, cy: 55, r: 5.7 },
  hubFill: "#C5CCD0",
  keys: "M38 44H42M29 55H32M48 55H51M39 65L42 63 39 61Z",
  keyFill: "#859099",
} as const;

/** The metal both Retro shells are filled with, and the dark both are lit on. */
export const RETRO_METAL = ["#FAFAF6", "#C1C9D0", "#F7F8F5", "#85919C"] as const;
export const RETRO_DARK = ["#56606F", "#252D39", "#101621"] as const;

/** Retro's controls: a jewel with an accent ring. */
export const RETRO_JEWEL = {
  body: { cx: 40, cy: 40, r: 31 },
  bodyStroke: "#737D8B",
  ring: { cx: 40, cy: 40, r: 26 },
  gloss: "M21 22Q40 10 59 22",
  ink: "#EFF3F1",
} as const;
