// Generated by scripts/build-icon-kits.py from the Gallery and Pocket Tech
// icon kits. Regenerate it rather than editing it.
//
// The pictograms are in curveKits.ts: all four curved kits draw the same
// subjects, and the generator refuses to emit anything if that stops being
// true. This file is only what sits behind them.
//
// Gallery is a glossy paint drop on warm paper, and the pigment is assigned per
// icon from a four-colour palette rather than per cluster — a rotation, so a
// screen of them reads as a painter's shelf rather than a legend. Pocket Tech
// is smoked glass and satin silver, one material for every icon, and its
// hierarchy is carried by the shape of the casing instead: a rounded shell for
// a cluster, a round jewel for a hobby.

// Gallery: one carrier for everything, and the pigment is the only variable.
//
// Clusters and hobbies are drawn the same way here, which is the kit's own
// decision and worth knowing: in this set the drawing does not say which is
// which, so the layout around it has to. Everywhere the app uses a mark today
// that is already true — Discover and Collection label every entry.
export const GALLERY_PIGMENT: Record<string, string> = {
  "3d-printing": "#9b651b",
  "adventure": "#c34b43",
  "archery": "#c34b43",
  "astronomy": "#26758d",
  "baking": "#7945c7",
  "birdwatching": "#c34b43",
  "blacksmithing": "#c34b43",
  "board-games": "#9b651b",
  "bookbinding": "#c34b43",
  "calligraphy": "#26758d",
  "chess": "#c34b43",
  "coding": "#c34b43",
  "coffee": "#26758d",
  "community": "#c34b43",
  "cooking": "#9b651b",
  "cooking-club": "#9b651b",
  "craft": "#7945c7",
  "creative": "#26758d",
  "culinary": "#26758d",
  "cycling": "#26758d",
  "drawing": "#c34b43",
  "electronics": "#7945c7",
  "fencing": "#9b651b",
  "fermentation": "#c34b43",
  "fitness": "#7945c7",
  "foraging": "#26758d",
  "genealogy": "#26758d",
  "geology": "#9b651b",
  "glassblowing": "#9b651b",
  "hiking": "#9b651b",
  "improv": "#7945c7",
  "investing": "#7945c7",
  "journaling": "#c34b43",
  "kayaking": "#7945c7",
  "language-learning": "#7945c7",
  "leatherwork": "#7945c7",
  "marine-biology": "#c34b43",
  "meditation": "#9b651b",
  "mind": "#26758d",
  "music": "#9b651b",
  "mycology": "#7945c7",
  "nature": "#9b651b",
  "outdoor": "#c34b43",
  "parkour": "#7945c7",
  "philosophy": "#26758d",
  "photography": "#26758d",
  "pottery": "#7945c7",
  "rock-climbing": "#9b651b",
  "running": "#9b651b",
  "skateboarding": "#26758d",
  "social": "#7945c7",
  "surfing": "#7945c7",
  "tech": "#9b651b",
  "urban-exploration": "#26758d",
  "volunteering": "#26758d",
  "weaving": "#26758d",
  "yoga": "#c34b43",
  "zumba": "#7945c7",
};


// Pocket Tech: a rounded shell for a cluster, a round jewel for a hobby.
//
// Three hobbies are drawn as a pocket player and one — photography — as a
// camera with no pictogram in it at all, the casing being the whole drawing.
// Both are the kit's decisions, detected rather than listed, so a kit that
// changes its mind is picked up on the next regeneration.
export const POCKET_PLAYERS: string[] = [
  "improv",
  "language-learning",
  "music",
];


export const POCKET_CAMERA: string[] = [
  "photography",
];


// The carriers, lifted verbatim.
//
// Gallery's are on a box centred at the origin, because that kit wraps
// everything in one translate(40 40); Pocket Tech's are on the plain 0..80 box
// the other kits use. `CURVE_BOX` covers both — what changes is whether the
// app recentres before scaling.
export const GALLERY_CENTRED = true;

/** Gallery's paint drop: an uneven blob, one wet highlight, white linework. */
export const GALLERY_DROP = {
  blob: "M0 -30C21 -31.5 32.7 -13.8 30 3.9C28.2 25.8 6 33.3-14.1 26.4C-36 18-34.5 -2.4-26.4 -18.3C-20.1 -29.1-9.9 -30 0 -30Z",
  highlight: "M-17.4 -16.8Q-4.5 -26.7 11.4 -20.7",
  highlightStroke: "#fff5e8",
  /** The wash the pigment lifts to, and the shadow it sinks into. */
  wash: "#d5b4eb",
  shade: "#402745",
  ink: "#fffdf8",
} as const;

export const GALLERY_GLYPH = { drop: 1.22, control: 2.1 } as const;
export const GALLERY_STROKE = 1.7;

/** Pocket Tech's three materials: satin silver, smoked glass, pale LCD. */
export const POCKET_SILVER = ["#fff", "#dce6ef", "#98acbd", "#f5f9fc"] as const;
export const POCKET_GLASS = ["#54687c", "#253447", "#0c1727"] as const;
export const POCKET_LCD = ["#d0eddf", "#718f83"] as const;
export const POCKET_STATUS = "#b8d7ad";

/** A cluster: a rounded shell with a status light under it. */
export const POCKET_SHELL = {
  body: { x: 10, y: 12, w: 60, h: 57, r: 22 },
  bodyStroke: "#8ba5bf",
  gloss: "M19 20Q40 10 61 20",
  glossStroke: "#d8edff",
  status: { cx: 40, cy: 62, r: 1.5 },
} as const;

/** A hobby: a round jewel, silver rim and smoked centre. */
export const POCKET_JEWEL = {
  rim: 29,
  face: 27.5,
  gloss: "M22 25Q40 13 58 25",
  glossStroke: "#e0f4ff",
} as const;

/** The pocket player, for the hobbies the kit draws that way. */
export const POCKET_PLAYER = {
  shell: { x: 20, y: 5, w: 40, h: 69, r: 12 },
  shellStroke: "#8194a7",
  screen: { x: 25, y: 11, w: 30, h: 24, r: 5 },
  ink: "#29453f",
  wheel: { cx: 40, cy: 54, r: 14 },
  wheelFill: "#f4f6f6",
  hub: { cx: 40, cy: 54, r: 5.6 },
  hubFill: "#d3dbe0",
  keys: "M38 43H42M29 54H32M48 54H51M39 63L42 61L39 59Z",
  keyFill: "#7a8c99",
} as const;

/** The camera, which is a whole drawing rather than a carrier for one. */
export const POCKET_CAMERA_BODY = {
  shell: "M12 25Q12 18 20 18H29L34 12H47L52 18H62Q70 18 70 27V58Q70 65 62 65H18Q10 65 10 57V29Q10 25 12 25Z",
  shellStroke: "#8499aa",
  back: { x: 13, y: 27, w: 54, h: 33, r: 9 },
  barrel: { cx: 40, cy: 43, r: 19 },
  glass: { cx: 40, cy: 43, r: 14 },
  glassFill: "#152939",
  iris: { cx: 40, cy: 43, r: 9 },
  irisFill: "#436a79",
  catchlight: "M34 40Q36 35 41 35",
  catchlightStroke: "#d5f1f0",
  flash: { x: 55, y: 21, w: 9, h: 4, r: 2 },
  flashFill: "#f3f4e4",
} as const;

export const POCKET_GLYPH = {
  shell: 1.75,
  jewel: 1.65,
  player: { x: 40, y: 23, scale: 0.72 },
  control: 2.25,
} as const;
export const POCKET_STROKE = 1.7;
